CREATE DATABASE SistemaAcademicoBCC
GO
USE SistemaAcademicoBCC
GO
CREATE TABLE tbCurso
(
	CUR_CODIGO int not null primary key identity,
	CUR_NOME varchar(50) not null,
	CUR_SIGLA varchar(5) null,
	CUR_CARGA_HORARIA int not null,
	CUR_NIVEL varchar(50) not null
)

CREATE TABLE tbDisciplina
(
	DIS_CODIGO int not null primary key identity,
	DIS_NOME varchar(50) not null,
	DIS_CARGA_HORARIA int not null,
	CUR_CODIGO int not null foreign key references tbCurso (CUR_CODIGO)
)
GO
CREATE TABLE tbProfessor
(
	PRO_CODIGO int not null primary key identity,
	PRO_NOME varchar(50) not null,
	PRO_EMAIL varchar(50) null,
	PRO_DATA_ADMISSAO datetime not null
)
GO
CREATE TABLE tbAluno
(
	ALU_CODIGO int not null primary key identity,
	ALU_NOME varchar(50) not null,
	ALU_MATRICULA int not null unique,
	ALU_CIDADE varchar(50) null,
	ALU_TELEFONE varchar(20) null,
	ALU_SEXO varchar(1) not null,
	CUR_CODIGO int not null references tbCurso (CUR_CODIGO)
)
GO
CREATE TABLE tbOfertaDisciplina
(
	ODI_CODIGO int not null primary key identity,
	DIS_CODIGO int not null foreign key references tbDisciplina (DIS_CODIGO),
	PRO_CODIGO int not null foreign key references tbProfessor (PRO_CODIGO),
	ODI_ANO int not null,
	ODI_SEMESTRE int not null,
	ODI_TURNO varchar(50) not null,	
	ODI_CAPACIDADE int not null
)
GO
CREATE TABLE tbAlunoMatricula
(
	ALD_CODIGO int not null primary key identity,
	ALU_CODIGO int not null foreign key references tbAluno (ALU_CODIGO),
	ODI_CODIGO int not null foreign key references tbOfertaDisciplina (ODI_CODIGO)
)
GO
INSERT INTO tbCurso
VALUES
('Bacharelado em Ciência da Computação', 'BCC', 3100, 'Graduação')
GO
INSERT INTO tbCurso
VALUES
('Técnico em Informática', 'INF', 1200, 'Técnico')
GO
INSERT INTO tbCurso
VALUES
('Técnico em Guia de Turismo', 'GTU', 1340, 'Técnico')
GO
INSERT INTO tbCurso
VALUES
('Técnico em Aquicultura', 'AQU', 1200, 'Técnico')
GO
INSERT INTO tbCurso
VALUES
('Tecnológo em Hotelaria', 'HOT', 2400, 'Graduação')
GO
INSERT INTO tbDisciplina
SELECT 'Português Instrumental', 40, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbDisciplina
SELECT 'Inglês Instrumental', 40, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbDisciplina
SELECT 'Introdução a Programação', 120, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbDisciplina
SELECT 'Cálculo I', 120, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbDisciplina
SELECT 'Estrutura de Dados', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbDisciplina
SELECT 'Banco de Dados I', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbDisciplina
SELECT 'Banco de Dados II', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbDisciplina
SELECT 'Cálculo II', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbDisciplina
SELECT 'Redes de Computadores I', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbDisciplina
SELECT 'Redes de Computadores II', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbDisciplina
SELECT 'Português Instrumental', 40, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')
GO
INSERT INTO tbDisciplina
SELECT 'Inglês Instrumental', 40, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')
GO
INSERT INTO tbDisciplina
SELECT 'Introdução a Programação', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')
GO
INSERT INTO tbDisciplina
SELECT 'Introdução a Redes', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')
GO
INSERT INTO tbDisciplina
SELECT 'Banco de Dados', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')
GO
INSERT INTO tbDisciplina
SELECT 'Prática Profissional', 40, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')
GO
INSERT INTO tbDisciplina
SELECT 'Montagem e Manutenção de Computadores', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')
GO
INSERT INTO tbDisciplina
SELECT 'Inglês I', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')
GO
INSERT INTO tbDisciplina
SELECT 'Inglês II', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')
GO
INSERT INTO tbDisciplina
SELECT 'Português Instrumental', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')
GO
INSERT INTO tbDisciplina
SELECT 'Prática de Guiamento Regional', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')
GO
INSERT INTO tbDisciplina
SELECT 'Prática de Guiamento Nacional', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')
GO
INSERT INTO tbDisciplina
SELECT 'História da América do Sul', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')
GO
INSERT INTO tbDisciplina
SELECT 'História do Brasil', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')
GO
INSERT INTO tbDisciplina
SELECT 'Geografia', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')
GO
INSERT INTO tbDisciplina
SELECT 'Português Instrumental', 40, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')
GO
INSERT INTO tbDisciplina
SELECT 'Informática Aplicada', 40, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')
GO
INSERT INTO tbDisciplina
SELECT 'Processamento de Pescado I', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')
GO
INSERT INTO tbDisciplina
SELECT 'Processamento de Pescado II', 40, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')
GO
INSERT INTO tbDisciplina
SELECT 'Microbiologia', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')
GO
INSERT INTO tbDisciplina
SELECT 'Biologia aquática', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')
GO
INSERT INTO tbDisciplina
SELECT 'Português Instrumental', 80, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbDisciplina
SELECT 'Inglês I', 40, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbDisciplina
SELECT 'Inglês II', 40, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbDisciplina
SELECT 'Espanhol I', 40, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbDisciplina
SELECT 'Espanhol II', 40, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbDisciplina
SELECT 'Introdução a Informática', 40, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbDisciplina
SELECT 'Gestão Hoteleira', 40, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbDisciplina
SELECT 'Alimentos e Bebidas', 40, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbDisciplina
SELECT 'Coquetelaria e Vinhos', 40, (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbProfessor
VALUES
('Raimundo Maciel', 'raimundo@gmail.com', '01/02/2010')
GO
INSERT INTO tbProfessor
VALUES
('Maria de Jesus', 'mariajesus90@hotmail.com.br', '05/04/2009')
GO
INSERT INTO tbProfessor
VALUES
('Paulo Albuquerque', 'pauloalbuquerque@gmail.com', '15/03/2012')
GO
INSERT INTO tbProfessor
VALUES
('Pedro Matias', 'matias@hotmail.com', '30/06/2007')
GO
INSERT INTO tbProfessor
VALUES
('João Cavalcante', 'jcavalcante@gmail.com', '11/02/2012')
GO
GO
INSERT INTO tbProfessor
VALUES
('Emanuel Sales', 'emanuelsales@hotmail.com', '11/02/2012')
GO
INSERT INTO tbProfessor
VALUES
('Carla da Silva', 'csilva@gmail.com', '15/03/2012')
GO
INSERT INTO tbProfessor
VALUES
('João Ananias', 'jananias@gmail.com', '28/04/2002')
GO
INSERT INTO tbProfessor
VALUES
('Marta Pereira', 'martapereira@gmail.com', '27/11/2008')
GO
INSERT INTO tbProfessor
VALUES
('Maria de Paula', 'mpaula@hotmail.com.br', '15/03/2012')
GO
INSERT INTO tbAluno
SELECT 'Ernesto Cesário', 20112893, 'Aracati', '(88)8823-2398', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbAluno
SELECT 'Angélica de Sousa', 20112892, 'Aracati', '(88)9214-2343', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbAluno
SELECT 'Rebeca Costa', 20112753, 'Aracati', '(88)9982-2398', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbAluno
SELECT 'Érica Andrade', 20121234, 'Aracati', '(88)9974-1253', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbAluno
SELECT 'Carolina de Sousa', 20121324, 'Aracati', '(85)9823-2343', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbAluno
SELECT 'Carlos Eduardo', 20112123, 'Fortim', '(88)9973-2873', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbAluno
SELECT 'Pedro de Alcântara', 20112345, 'Aracati', '(88)9645-9843', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbAluno
SELECT 'Carlos Augusto', 20112094, 'Icapuí', '(84)9823-4234', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbAluno
SELECT 'Mateus Alves', 20121675, 'Fortim', '(85)9834-9348', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbAluno
SELECT 'Mônica Azevedo', 20112234, 'Icapuí', '(88)9845-4985', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbAluno
SELECT 'Marta Morais', 201219384, 'Fortim', '(88)9349-0943', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')
GO
INSERT INTO tbAluno
SELECT 'Bruno da Silva', 20121983, 'Aracati', '(88)3421-2398', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')
GO
INSERT INTO tbAluno
SELECT 'Patrícia Vasconcelos', 20112122, 'Aracati', '(88)9834-3498', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')
GO
INSERT INTO tbAluno
SELECT 'Paulo Augusto', 2012139843, 'Aracati', '(88)9843-9438', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')
GO
INSERT INTO tbAluno
SELECT 'Carina Araújo', 201212323, 'Aracati', '(88)8754-0954', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')
GO
INSERT INTO tbAluno
SELECT 'Francisco Augusto', 20112323, 'Icapuí', '(88)9384-9854', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')
GO
INSERT INTO tbAluno
SELECT 'Josiane Andrade', 20112098, 'Icapuí', '(88)9834-9384', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')
GO
INSERT INTO tbAluno
SELECT 'Maicon Pedro', 20121654, 'Aracati', '(88)9934-4934', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')
GO
INSERT INTO tbAluno
SELECT 'Lucas Silva', 20112299, 'Icapuí', '(84)9235-2345', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')
GO
INSERT INTO tbAluno
SELECT 'Priscila Dantas', 20112212, 'Aracati', '(88)9653-9384', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')
GO
INSERT INTO tbAluno
SELECT 'Jeferson Linhares', 20121232, 'Icapuí', '(84)9934-9384', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')
GO
INSERT INTO tbAluno
SELECT 'Jaqueline Andrade', 20121975, 'Icapuí', '(88)9934-9384', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')
GO
INSERT INTO tbAluno
SELECT 'Emanuel Sousa', 20122234, 'Aracati', '(88)8765-9384', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')
GO
INSERT INTO tbAluno
SELECT 'Marcos Pereira', 20122123, 'Icapuí', '(84)8087-0987', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')
GO
INSERT INTO tbAluno
SELECT 'Maria Amélia', 20122987, 'Aracati', '(88)9845-5467', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')
GO
INSERT INTO tbAluno
SELECT 'Maria Aparecida', 20122646, 'Aracati', '(88)9467-1212', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')
GO
INSERT INTO tbAluno
SELECT 'Maria Joaquina', 20122018, 'Aracati', '(88)8080-1234', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')
GO
INSERT INTO tbAluno
SELECT 'Pedro Emanuel', 20122763, 'Aracati', '(88)8181-1234', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbAluno
SELECT 'João Carlos', 20122001, 'Aracati', '(85)9898-1200', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbAluno
SELECT 'Aurélio Dantas', 20122345, 'Aracati', '(88)8888-1234', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbAluno
SELECT 'René Duarte', 20122098, 'Aracati', '(85)9983-0098', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbAluno
SELECT 'João Carlos', 20122876, 'Fortim', '(88)8375-5456', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbAluno
SELECT 'Érica Albuquerque', 20122456, 'Aracati', '(88)9834-0032', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbAluno
SELECT 'Carolina Oliveira', 20122284, 'Aracati', '(88)8734-8732', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbAluno
SELECT 'Antônio Eduardo', 20122153, 'Aracati', '(88)4356-4455', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbAluno
SELECT 'Vinícius de Morais', 20122985, 'Aracati', '(88)9345-0109', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbAluno
SELECT 'João Alan', 20122082, 'Aracati', '(88)9823-8732', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')
GO
INSERT INTO tbAluno
SELECT 'Romeu Augusto', 20122872, 'Fortim', '(88)8734-0005', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')
GO
INSERT INTO tbAluno
SELECT 'Breno Araújo', 20122989, 'Aracati', '(88)8734-8732', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')
GO
INSERT INTO tbAluno
SELECT 'Ananias Andrade', 20122946, 'Aracati', '(88)9734-8231', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')
GO
INSERT INTO tbAluno
SELECT 'Lúcio Silva', 20122943, 'Aracati', '(88)9734-8723', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')
GO
INSERT INTO tbAluno
SELECT 'Lúcia Marinho', 20122005, 'Aracati', '(88)9900-8732', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')
GO
INSERT INTO tbAluno
SELECT 'Rafael Marinho', 20122007, 'Aracati', '(88)9905-8892', 'M', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')
GO
INSERT INTO tbAluno
SELECT 'Rafaela Joaquina', 20122012, 'Aracati', '(88)9590-1294', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')
GO
INSERT INTO tbAluno
SELECT 'Adriana Pereira', 20122087, 'Aracati', '(88)9350-1993', 'F', (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Raimundo Maciel'),
	   2014, 2, 'TARDE', 40
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Raimundo Maciel'),
	   2014, 2, 'TARDE', 40
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Raimundo Maciel'),
	   2014, 2, 'TARDE', 40
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Raimundo Maciel'),
	   2014, 2, 'TARDE', 40
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Raimundo Maciel'),
	   2014, 2, 'TARDE', 40
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Inglês Instrumental' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Maria de Jesus'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Inglês Instrumental' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Maria de Jesus'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Inglês I' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Maria de Jesus'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Inglês I' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Maria de Jesus'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Inglês II' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Maria de Jesus'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Introdução a Programação' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Paulo Albuquerque'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Introdução a Programação' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Paulo Albuquerque'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Estrutura de Dados' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Paulo Albuquerque'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Banco de Dados I' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Paulo Albuquerque'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Banco de Dados II' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Paulo Albuquerque'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Banco de Dados' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Paulo Albuquerque'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Cálculo I' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Pedro Matias'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Cálculo II' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Pedro Matias'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Redes de Computadores I' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'João Cavalcante'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Informática Aplicada' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'João Cavalcante'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Redes de Computadores II' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'João Cavalcante'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Prática de Guiamento Regional' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Carla da Silva'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'História da América do Sul' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'João Ananias'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'História do Brasil' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'João Ananias'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Processamento de Pescado I' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Marta Pereira'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Gestão Hoteleira' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Maria de Paula'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Alimentos e Bebidas' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Maria de Paula'),
	   2014, 2, 'TARDE', 40	
GO
INSERT INTO tbOfertaDisciplina
SELECT (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Coquetelaria e Vinhos' AND CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')),
	   (SELECT PRO_CODIGO FROM tbProfessor WHERE PRO_NOME = 'Maria de Paula'),
	   2014, 2, 'TARDE', 40	
GO
UPDATE tbOfertaDisciplina
SET ODI_TURNO = 'NOITE'
WHERE
DIS_CODIGO IN (SELECT DIS_CODIGO FROM tbDisciplina D JOIN tbCurso C ON D.CUR_CODIGO = C.CUR_CODIGO 
				WHERE CUR_SIGLA = 'HOT')
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112893), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112893), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Inglês Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112893), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Introdução a Programação' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112893), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Cálculo I' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112892), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112892), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Cálculo I' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112892), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Introdução a Programação' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112753), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112753), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Introdução a Programação' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112753), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Banco de Dados I' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20121234), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20121234), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Estrutura de Dados' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20121234), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Banco de Dados II' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20121234), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Cálculo II' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20121324), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20121324), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Redes de Computadores I' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112123), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112123), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Redes de Computadores II' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112094), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Banco de Dados II' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112094), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Redes de Computadores II' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20121675), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Banco de Dados I' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20121675), --BCC
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Inglês Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'BCC')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 201219384), --INF
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 201219384), --INF
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Introdução a Programação' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 201219384), --INF
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Banco de Dados' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20121983), --INF
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Inglês Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20121983), --INF
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Introdução a Programação' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112122), --INF
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Banco de Dados' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112122), --INF
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Introdução a Programação' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 2012139843), --INF
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 2012139843), --INF
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Inglês Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 201212323), --INF
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Introdução a Programação' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 201212323), --INF
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Banco de Dados' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112098), --INF
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112098), --INF
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Introdução a Programação' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'INF')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20121232), --AQU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20121232), --AQU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Processamento de Pescado I' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112212), --AQU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Processamento de Pescado I' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112212), --AQU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Informática Aplicada' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20112212), --AQU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Processamento de Pescado I' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20121975), --AQU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Informática Aplicada' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20121975), --AQU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122234), --AQU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Processamento de Pescado I' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122943), --AQU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Informática Aplicada' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'AQU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122123), --GTU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'História do Brasil' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122123), --GTU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Inglês I' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122987), --GTU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122646), --GTU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Prática de Guiamento Regional' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122646), --GTU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'História da América do Sul' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122018), --GTU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'História do Brasil' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122018), --GTU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Prática de Guiamento Regional' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122087), --GTU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Prática de Guiamento Regional' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122012), --GTU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português INstrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122012), --GTU
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'História do Brasil' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'GTU')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122763), --HOT
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Coquetelaria e Vinhos' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122763), --HOT
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Gestão Hoteleira' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122001), --HOT
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122345), --HOT
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Inglês I' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122345), --HOT
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122098), --HOT
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Coquetelaria e Vinhos' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122098), --HOT
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Gestão Hoteleira' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122098), --HOT
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Alimentos e Bebidas' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122876), --HOT
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Coquetelaria e Vinhos' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122876), --HOT
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Português Instrumental' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')))
GO
INSERT INTO tbAlunoMatricula
SELECT (SELECT ALU_CODIGO FROM tbAluno WHERE ALU_MATRICULA = 20122876), --HOT
	   (SELECT ODI_CODIGO FROM tbOfertaDisciplina WHERE DIS_CODIGO = 
	   (SELECT DIS_CODIGO FROM tbDisciplina WHERE DIS_NOME = 'Inglês I' AND 
	   CUR_CODIGO = (SELECT CUR_CODIGO FROM tbCurso WHERE CUR_SIGLA = 'HOT')))